// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbAsV4kNKUkMtjI5ggXNj7XIiEwFnElG8',
    appId: '1:508444551078:web:ea63a5a690f1c2d464d167',
    messagingSenderId: '508444551078',
    projectId: 'krashidhara',
    authDomain: 'krashidhara.firebaseapp.com',
    storageBucket: 'krashidhara.appspot.com',
    measurementId: 'G-JZWJ4809Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPNr29eiZyNiu2mNR2j4BywWk0B9PYUjI',
    appId: '1:508444551078:android:ac44b1d3943f58a464d167',
    messagingSenderId: '508444551078',
    projectId: 'krashidhara',
    storageBucket: 'krashidhara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk2VZBAPi-k8K-X4D680Jnu-aQPgj_iKw',
    appId: '1:508444551078:ios:45c6586a2142872964d167',
    messagingSenderId: '508444551078',
    projectId: 'krashidhara',
    storageBucket: 'krashidhara.appspot.com',
    iosClientId: '508444551078-607bnobm2jql4a9qk67ip6lmp7asvndn.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk2VZBAPi-k8K-X4D680Jnu-aQPgj_iKw',
    appId: '1:508444551078:ios:45c6586a2142872964d167',
    messagingSenderId: '508444551078',
    projectId: 'krashidhara',
    storageBucket: 'krashidhara.appspot.com',
    iosClientId: '508444551078-607bnobm2jql4a9qk67ip6lmp7asvndn.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRent',
  );
}
